version: "2.3"
services:
  elixir-omg:
    image: omisegoimages/elixir-omg-builder:stable-20200410
    environment:
      DATABASE_URL: postgres://omisego_dev:omisego_dev@postgres:5432/omisego_dev
    volumes:
      - .:/app
  watcher:
    environment:
      - DD_DISABLED=false
    depends_on:
      datadog:
        condition: service_healthy
  watcher_info:
    environment:
      - DD_DISABLED=false
    depends_on:
      datadog:
        condition: service_healthy
  childchain:
    environment:
      - DD_DISABLED=false
    depends_on:
      datadog:
        condition: service_healthy
  datadog:
    image: datadog/agent:latest
    restart: always
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_TAGS=["env:local_development"]
      #- DD_LOG_LEVEL=debug
      - DOCKER_CONTENT_TRUST=1
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126/tcp"

  # Submits an Ethereum transaction with a random gas price between 1 - $MAX_GAS_PRICE_GWEI Gwei
  # every $SLEEP_SECONDS interval
  geth-random-gas-price-tx-factory:
    image: curlimages/curl:7.71.0
    command: >
      sh -c '
        while true
        do
          TX_AMOUNT_GWEI=$$((1 + RANDOM % 10))
          TX_AMOUNT_WEI=$$(($$TX_AMOUNT_GWEI*1000000000))
          TX_AMOUNT_HEX="0x$$(printf "%x" '$$TX_AMOUNT_WEI')"

          GAS_PRICE_GWEI=$$((1 + RANDOM % $$MAX_GAS_PRICE_GWEI))
          GAS_PRICE_WEI=$$(($$GAS_PRICE_GWEI*1000000000))
          GAS_PRICE_HEX="0x$$(printf "%x" '$$GAS_PRICE_WEI')"
          echo Submitting $$TX_AMOUNT_GWEI Gwei tx with gas price of $$GAS_PRICE_GWEI Gwei

          curl -s -X POST http://geth:8545 \
            -H "Content-Type: application/json" \
            --data "{
                \"jsonrpc\": \"2.0\",
                \"method\": \"eth_sendTransaction\",
                \"params\": [{
                  \"from\": \"0x6de4b3b9c28e9c3e84c2b2d3a875c947a84de68d\",
                  \"to\": \"0x6de4b3b9c28e9c3e84c2b2d3a875c947a84de68d\",
                  \"gasPrice\": \"'$$GAS_PRICE_HEX'\",
                  \"value\": \"'$$TX_AMOUNT_HEX'\"
                  }],
                \"id\":1
              }"

          sleep $$SLEEP_SECONDS
        done
      '
    environment:
      - MAX_GAS_PRICE_GWEI=100
      - SLEEP_SECONDS=10
